### ISSUE TITLE
joystick in flags error

### ISSUE THREAD

**Issue by daggs1-zz** [ngld/old-knossos#170]
Greetings,

I'm using knossos-0.14.0-rc.1, I have Thrustmaster T.Flight Hotas X, ever since I've plugged it and run the launcher, I cannot run any game, I get this errors:
```
INFO:Thread-16:util.check_output: Running ['/home/dagg/games/FreespaceOpen/bin/FSO-3.8.0-3/fs2_open_3_8_0_x64.AppImage', '-get_flags', 'json_v1', '-parse_cmdline_only']
ERROR:Thread-16:settings.get_fso_flags: Failed to read JSON printed by FSO: Expecting value: line 1 column 1 (char 0)
INFO:Thread-16:util.check_output: Running ['/home/dagg/games/FreespaceOpen/bin/FSO-3.8.0-3/fs2_open_3_8_0_x64.AppImage', '-get_flags', 'binary', '-parse_cmdline_only']
ERROR:Thread-16:settings.get_fso_flags: Could not find the flags file "/home/dagg/games/FreespaceOpen/flags.lch"!
Exception in thread Thread-16:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/dagg/workspace/diasporar1/knossos-0.14.0-rc.1/knossos/runner.py", line 90, in run
    if not self.prepare_fso_config(fs2_bin):
  File "/home/dagg/workspace/diasporar1/knossos-0.14.0-rc.1/knossos/runner.py", line 151, in prepare_fso_config
    if 'joysticks' in flags:
TypeError: argument of type 'NoneType' is not iterable
```
any ideas?

**Comment by ngld** [comment]
Try installing a recent nightly: Go to settings and set your preferred stability to "nightly", save go to the Home tab and update FSO.

Also, what happens if you directly run `/home/dagg/games/FreespaceOpen/bin/FSO-3.8.0-3/fs2_open_3_8_0_x64.AppImage -get_flags binary -parse_cmdline_only`?

**Comment by daggs1-zz** [comment]
looks like it worked, thanks;.
