### ISSUE TITLE
Can't see mods after enabling Show Engine Builds in Mod List

### ISSUE THREAD

**Issue by chief1983** [ngld/old-knossos#196]
If I enable Show Engine Builds in Mod List, and then go to the Explore, I only see the engine builds.  I also see this in the debug log whereas it wasn't there before:

```DEBUG:MainThread:windows.watch_task: Task "Loading installed mods..." (140351201127160, <class 'knossos.tasks.LoadLocalModsTask'>) started.
QJson: Document too large to store in data structure
DEBUG:MainThread:windows.watch_task: Task "Fetching mod list..." (140350132708264, <class 'knossos.tasks.FetchTask'>) started.
DEBUG:MainThread:windows.watch_task: Task "Checking for updates..." (140350132708408, <class 'knossos.tasks.CheckUpdateTask'>) started.
ERROR:MainThread:web.reportError: JS Error: TypeError: Cannot read property 't' of null
    at qrc:///html/dist/bundle.js:39:166392
    at Object.<anonymous> (qrc:///qtwebchannel/qwebchannel.js:353:35)
    at QWebChannel.handleResponse (qrc:///qtwebchannel/qwebchannel.js:137:42)
    at Object.QWebChannel.transport.onmessage (qrc:///qtwebchannel/qwebchannel.js:86:25)
DEBUG:MainThread:base.send_remote: Sending message of length 3997 to https://sentry.gruenprint.de/api/9/store/
DEBUG:raven.AsyncWorker:connectionpool._new_conn: Starting new HTTPS connection (1): sentry.gruenprint.de:443
DEBUG:MainThread:windows._forget_task: Task "Loading installed mods..." (140351201127160) finished.
js: Uncaught TypeError: Cannot read property 't' of null
DEBUG:Thread-1:progress._next_step: Entering step 1 of 2 in task FetchTask.
DEBUG:Thread-9:connectionpool._new_conn: Starting new HTTPS connection (1): cf.fsnebula.org:443
DEBUG:Thread-9:connectionpool._make_request: https://cf.fsnebula.org:443 "GET /storage/repo.json HTTP/1.1" 200 None
DEBUG:raven.AsyncWorker:connectionpool._make_request: https://sentry.gruenprint.de:443 "POST /api/9/store/ HTTP/1.1" 200 None
```

MacOS 10.15.5
Knossos 0.14.1

**Comment by chief1983** [comment]
Appears to have simply been one of the ways to break the mod list that was fixed in 0.14.3.  Closing.
