### ISSUE TITLE
MVPS is missing

### ISSUE THREAD

**Issue by valerahime** [ngld/old-knossos#209]
I'm trying to install the Trimurti mod, however I receive this error:

`I'm sorry but you won't be able to install "Trimurti" because "MVPS" is missing!`

The log reads:

```
ERROR:MainThread:windows.show_packages: Well, I won't be installing that...
Traceback (most recent call last):
  File "C:\knossos\knossos\windows.py", line 679, in show_packages
  File "C:\knossos\knossos\repo.py", line 385, in process_pkg_selection
knossos.repo.PackageConstraintNotMet: No version of mod "Freespace Upgrade MediaVPs" found for these constraints: ~3.7.2 (Trimurti),~4.3.3 (FreeSpace Port MediaVPs)
```

However, I have versions 3.7.2 and 4.3.3 installed for FS2 MediaVPs, and 3.7.2 and 4.3.2 installed for FS1 MediaVPs. Not sure what's causing the error. Is it the `~4.3.3 (FreeSpace Port MediaVPs)`?

**Comment by valerahime** [comment]
This seems to have been fixed.
