### ISSUE TITLE
Knossos not starting after a clean install

### ISSUE THREAD

**Issue by Hellzed** [ngld/old-knossos#38]
Hi!
I'm running Ubuntu 17.04, this is a clean install. I've installed the dependencies and build Knossos, however I'm running into the following error. I suspect some default keys are missing from the settings object:
```$ ninja debug
[0/1] DEBUG
INFO:MainThread:launcher.main: Running Knossos 0.5.0-dev on PyQt5.
DEBUG:MainThread:launcher.main: Loading resources from /home/loris/Code/knossos/knossos/data/resources.rcc.
DEBUG:MainThread:launcher.main: Loading settings...
ERROR:MainThread:launcher.my_excepthook: UNCAUGHT EXCEPTION!
Traceback (most recent call last):
  File "/home/loris/Code/knossos/knossos/__main__.py", line 123, in <module>
    launcher.main()
  File "/home/loris/Code/knossos/knossos/launcher.py", line 287, in main
    load_settings()
  File "/home/loris/Code/knossos/knossos/launcher.py", line 145, in load_settings
    if '#default' not in settings['cmdlines']:
KeyError: 'cmdlines'
FAILED: debug 
KN_BABEL=False KN_DEBUG=1 QTWEBENGINE_REMOTE_DEBUGGING=4006 /home/loris/Code/knossos/knossos-virt/bin/python /home/loris/Code/knossos/knossos/__main__.py
ninja: build stopped: subcommand failed.
```

**Comment by ngld** [comment]
Thanks for reporting! It should be fixed now.
